# Generated by Django 4.2.7 on 2023-11-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('book_title', models.CharField(max_length=200)),
                ('publication_date', models.DateField(auto_now=True)),
                ('cover_image', models.ImageField(blank=True, max_length=200, upload_to='book_covers')),
                ('pdf_book', models.FileField(blank=True, max_length=200, upload_to='pdf_books')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
    ]
