# Generated by Django 4.2.7 on 2023-11-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_rename_category_name_school_school_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atu_logo', models.FileField(blank=True, upload_to='atu_logo')),
            ],
        ),
    ]
