# Generated by Django 4.2.7 on 2023-11-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='atu_logo',
            field=models.ImageField(blank=True, upload_to='atu_logo'),
        ),
    ]
