# Generated by Django 4.2.7 on 2023-11-29 10:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lab", "0007_alter_logo_atu_logo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
    ]
