# Generated by Django 4.2.7 on 2023-11-29 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lab", "0008_alter_category_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Logo",
        ),
        migrations.DeleteModel(
            name="School",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="cover_image",
            new_name="cover",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="publication_date",
            new_name="published_at",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="pdf_book",
            new_name="src_pdf",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="book_title",
            new_name="title",
        ),
        migrations.AddField(
            model_name="book",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
