# Generated by Django 4.2.7 on 2023-12-10 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lab", "0010_book_summary_collection"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="src_pdf",
            new_name="file",
        ),
    ]
